name: safezone_mobile
description: SafeZone+ Campus Safety Mobile App

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2
  # WebSocket for real-time communication
  web_socket_channel: ^2.4.0
  # Location services
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  # Google Maps
  google_maps_flutter: ^2.5.0
  # HTTP requests
  http: ^1.1.0
  # Local storage
  shared_preferences: ^2.2.2
  # Image picker for camera/gallery
  image_picker: ^1.0.4
  # Camera for face verification
  camera: ^0.10.5+5
  # Image processing
  image: ^4.1.3
  # Socket.IO client for real-time updates
  socket_io_client: ^2.0.0
  # Pin to 6.2.1 to match existing GoogleSignIn API used in the app code
  google_sign_in: 6.2.1
  dropdown_button2: ^2.3.9 
  shimmer: ^3.0.0
  # URL launcher for opening maps
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    # App icon used by flutter_launcher_icons
    - ../../assets/icon.png

# flutter_launcher_icons config to generate native app icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"


